# Generated by Django 6.0 on 2025-12-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_profil', models.CharField(choices=[('jeune', "Jeune en quête d'emploi"), ('retraite', 'Retraité actif')], max_length=10)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=150)),
                ('sexe', models.CharField(choices=[('masculin', 'Masculin'), ('feminin', 'Féminin'), ('autre', 'Autre')], max_length=10)),
                ('date_naissance', models.DateField()),
                ('nationalite', models.CharField(blank=True, max_length=100)),
                ('telephone1', models.CharField(max_length=30)),
                ('telephone2', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('quartier', models.CharField(max_length=255)),
                ('canton', models.CharField(blank=True, max_length=100)),
                ('adresse_complete', models.TextField()),
                ('est_resident_kloto', models.BooleanField(default=True, help_text='Cochez si la personne réside dans la commune de Kloto 1.')),
                ('niveau_etude', models.CharField(blank=True, choices=[('aucun', 'Aucun diplôme formel'), ('cep', 'CEP'), ('bepc', 'BEPC'), ('bac', 'BAC'), ('bts', 'BTS / DUT'), ('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('autre', 'Autre')], max_length=20)),
                ('diplome_principal', models.CharField(blank=True, max_length=150)),
                ('domaine_competence', models.TextField(help_text='Compétences principales, métiers.')),
                ('experiences', models.TextField(blank=True, help_text='Brève description des expériences professionnelles.')),
                ('situation_actuelle', models.CharField(choices=[('sans_emploi', 'Sans emploi'), ('en_emploi', 'En emploi'), ('etudiant', 'Étudiant'), ('retraite', 'Retraité'), ('autre', 'Autre')], default='sans_emploi', max_length=20)),
                ('employeur_actuel', models.CharField(blank=True, max_length=255)),
                ('disponibilite', models.CharField(choices=[('immediate', 'Immédiate'), ('1_mois', 'Sous 1 mois'), ('3_mois', 'Sous 3 mois'), ('autre', 'Autre')], default='immediate', max_length=20)),
                ('type_contrat_souhaite', models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('mission', 'Mission / Temps partiel'), ('benevolat', 'Bénévolat')], max_length=20)),
                ('salaire_souhaite', models.CharField(blank=True, max_length=50)),
                ('dernier_poste', models.CharField(blank=True, help_text='Dernier poste occupé (surtout pour les retraités).', max_length=255)),
                ('annees_experience', models.PositiveIntegerField(blank=True, help_text="Nombre d'années d'expérience.", null=True)),
                ('accepte_rgpd', models.BooleanField(default=False, help_text="J'accepte que mes données soient traitées par la Mairie de Kloto 1.")),
                ('accepte_contact', models.BooleanField(default=False, help_text="J'accepte d'être contacté par des employeurs via la plateforme.")),
                ('est_valide_par_mairie', models.BooleanField(default=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profil emploi',
                'verbose_name_plural': 'Profils emploi',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
