# Generated by Django 6.0 on 2025-12-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemploi',
            name='caisse_retraite',
            field=models.CharField(blank=True, help_text='Caisse de retraite / régime de pension (CNSS, CACIT, etc.).', max_length=150),
        ),
    ]
