# Generated by Django 6.0 on 2025-12-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActeurEconomique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=255)),
                ('type_acteur', models.CharField(choices=[('entreprise', 'Entreprise'), ('commerce', 'Commerce'), ('artisan', 'Artisan'), ('pme', 'PME'), ('pmi', 'PMI'), ('ong', 'ONG'), ('association', 'Association'), ('autre', 'Autre')], max_length=20)),
                ('secteur_activite', models.CharField(choices=[('commerce', 'Commerce général'), ('artisanat', 'Artisanat'), ('service', 'Services'), ('industrie', 'Industrie'), ('agriculture', 'Agriculture'), ('batiment', 'Bâtiment et Travaux Publics'), ('transport', 'Transport'), ('technologie', 'Technologie et Informatique'), ('sante', 'Santé'), ('education', 'Éducation et Formation'), ('hotellerie', 'Hôtellerie et Restauration'), ('finance', 'Finance et Assurance'), ('autre', 'Autre')], max_length=30)),
                ('statut_juridique', models.CharField(choices=[('sarl', 'SARL - Société à Responsabilité Limitée'), ('sa', 'SA - Société Anonyme'), ('ei', 'EI - Entreprise Individuelle'), ('snc', 'SNC - Société en Nom Collectif'), ('association', 'Association'), ('ong', 'ONG'), ('cooperative', 'Coopérative'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('rccm', models.CharField(blank=True, max_length=100)),
                ('ifu', models.CharField(blank=True, max_length=100)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('nom_responsable', models.CharField(max_length=255)),
                ('fonction_responsable', models.CharField(max_length=255)),
                ('telephone1', models.CharField(max_length=30)),
                ('telephone2', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('quartier', models.CharField(max_length=255)),
                ('canton', models.CharField(blank=True, max_length=100)),
                ('adresse_complete', models.TextField()),
                ('nombre_employes', models.CharField(blank=True, choices=[('1-5', '1 à 5'), ('6-10', '6 à 10'), ('11-50', '11 à 50'), ('51-100', '51 à 100'), ('100+', 'Plus de 100')], max_length=20)),
                ('chiffre_affaires', models.CharField(blank=True, choices=[('0-5M', 'Moins de 5 millions'), ('5M-20M', '5 à 20 millions'), ('20M-50M', '20 à 50 millions'), ('50M-100M', '50 à 100 millions'), ('100M+', 'Plus de 100 millions')], max_length=20)),
                ('doc_registre', models.FileField(blank=True, upload_to='documents/registre/')),
                ('doc_ifu', models.FileField(blank=True, upload_to='documents/ifu/')),
                ('autres_documents', models.FileField(blank=True, null=True, upload_to='documents/autres/')),
                ('accepte_public', models.BooleanField(default=False)),
                ('certifie_information', models.BooleanField(default=False)),
                ('accepte_conditions', models.BooleanField(default=False)),
                ('est_valide_par_mairie', models.BooleanField(default=False)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Acteur économique',
                'verbose_name_plural': 'Acteurs économiques',
                'ordering': ['-date_enregistrement'],
            },
        ),
    ]
