# Generated by Django 6.0 on 2025-12-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionFinanciere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_institution', models.CharField(choices=[('banque', 'Banque commerciale'), ('microfinance', 'Institution de microfinance (IMF)'), ('bailleur', 'Bailleur de fonds'), ('ong', 'ONG de financement'), ('cooperative', "Coopérative d'épargne et de crédit"), ('assurance', "Compagnie d'assurance"), ('investissement', "Société d'investissement"), ('autre', 'Autre')], max_length=30)),
                ('nom_institution', models.CharField(max_length=255)),
                ('sigle', models.CharField(blank=True, max_length=50)),
                ('annee_creation', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_agrement', models.CharField(blank=True, max_length=100)),
                ('ifu', models.CharField(blank=True, max_length=100)),
                ('description_services', models.TextField()),
                ('services', models.CharField(blank=True, max_length=255)),
                ('taux_credit', models.CharField(blank=True, max_length=50)),
                ('taux_epargne', models.CharField(blank=True, max_length=50)),
                ('nom_responsable', models.CharField(max_length=255)),
                ('fonction_responsable', models.CharField(max_length=255)),
                ('telephone1', models.CharField(max_length=30)),
                ('telephone2', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('quartier', models.CharField(max_length=255)),
                ('canton', models.CharField(blank=True, max_length=100)),
                ('adresse_complete', models.TextField()),
                ('nombre_agences', models.PositiveIntegerField(blank=True, null=True)),
                ('horaires', models.CharField(max_length=255)),
                ('doc_agrement', models.FileField(blank=True, upload_to='institutions/agrements/')),
                ('logo', models.FileField(blank=True, upload_to='institutions/logos/')),
                ('brochure', models.FileField(blank=True, upload_to='institutions/brochures/')),
                ('conditions_eligibilite', models.TextField(blank=True)),
                ('public_cible', models.TextField(blank=True)),
                ('certifie_info', models.BooleanField(default=False)),
                ('accepte_public', models.BooleanField(default=False)),
                ('accepte_contact', models.BooleanField(default=False)),
                ('engagement', models.BooleanField(default=False)),
                ('est_valide_par_mairie', models.BooleanField(default=False)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Institution financière',
                'verbose_name_plural': 'Institutions financières',
                'ordering': ['-date_enregistrement'],
            },
        ),
    ]
