# Generated by Django 6.0 on 2025-12-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acteurs', '0002_institutionfinanciere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acteureconomique',
            old_name='ifu',
            new_name='cfe',
        ),
        migrations.AddField(
            model_name='acteureconomique',
            name='nif',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='acteureconomique',
            name='numero_carte_operateur',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='institutionfinanciere',
            name='type_institution',
            field=models.CharField(choices=[('banque', 'Banque commerciale'), ('microfinance', 'Institution de microfinance (IMF)'), ('bailleur', 'Bailleur de fonds'), ('ong', 'ONG de financement'), ('association', 'Association'), ('fondation', 'Fondation'), ('cooperative', "Coopérative d'épargne et de crédit"), ('assurance', "Compagnie d'assurance"), ('investissement', "Société d'investissement"), ('autre', 'Autre')], max_length=30),
        ),
    ]
