# Generated by Django 6.0 on 2025-12-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acteurs', '0003_rename_ifu_acteureconomique_cfe_acteureconomique_nif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTouristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(max_length=255)),
                ('categorie_site', models.CharField(choices=[('cascade', 'Cascade'), ('montagne', 'Montagne'), ('foret', 'Forêt'), ('plage', 'Plage'), ('parc', 'Parc'), ('monument', 'Monument'), ('musee', 'Musée'), ('site_culturel', 'Site culturel'), ('site_historique', 'Site historique'), ('autre', 'Autre')], max_length=30)),
                ('description', models.TextField()),
                ('particularite', models.TextField(blank=True)),
                ('prix_visite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horaires_visite', models.CharField(max_length=255)),
                ('jours_ouverture', models.CharField(blank=True, max_length=255)),
                ('quartier', models.CharField(max_length=255)),
                ('canton', models.CharField(blank=True, max_length=100)),
                ('adresse_complete', models.TextField()),
                ('coordonnees_gps', models.CharField(blank=True, max_length=100)),
                ('guide_disponible', models.BooleanField(default=False)),
                ('parking_disponible', models.BooleanField(default=False)),
                ('restauration_disponible', models.BooleanField(default=False)),
                ('acces_handicapes', models.BooleanField(default=False)),
                ('telephone_contact', models.CharField(blank=True, max_length=30)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('photo_principale', models.FileField(blank=True, upload_to='sites/photos/')),
                ('conditions_acces', models.TextField(blank=True)),
                ('est_valide_par_mairie', models.BooleanField(default=False)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site touristique',
                'verbose_name_plural': 'Sites touristiques',
                'ordering': ['-date_enregistrement'],
            },
        ),
        migrations.AlterField(
            model_name='acteureconomique',
            name='secteur_activite',
            field=models.CharField(choices=[('commerce', 'Commerce général'), ('artisanat', 'Artisanat'), ('service', 'Services'), ('industrie', 'Industrie'), ('agriculture', 'Agriculture'), ('batiment', 'Bâtiment et Travaux Publics'), ('transport', 'Transport'), ('technologie', 'Technologie et Informatique'), ('sante', 'Santé'), ('education', 'Éducation et Formation'), ('hotellerie', 'Hôtellerie et Restauration'), ('finance', 'Finance et Assurance'), ('bar', 'Bar'), ('restaurant', 'Restaurant'), ('auberge', 'Auberge'), ('traiteur', 'Service Traiteur'), ('pharmacie', 'Pharmacie'), ('depot_pharmacie', 'Dépôt de Pharmacie'), ('ecole_publique', 'Écoles Publiques'), ('ecole_privee', 'Écoles Privées'), ('supermarche', 'Supermarché'), ('boutique', 'Boutique'), ('alimentation', 'Alimentation générale'), ('pret_a_porter', 'Prêt-à-porter'), ('quincaillerie', 'Quincaillerie'), ('tourisme', 'Tourisme'), ('autre', 'Autre')], max_length=30),
        ),
    ]
