# Generated by Django 6.0 on 2026-01-03 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acteurs', '0004_sitetouristique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acteureconomique',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acteur_economique', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionfinanciere',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_financiere', to=settings.AUTH_USER_MODEL),
        ),
    ]
