# Generated by Django 6.0 on 2026-01-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acteurs', '0005_acteureconomique_user_institutionfinanciere_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='acteureconomique',
            name='sigle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
