# Generated by Django 6.0.1 on 2026-01-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acteurs', '0007_acteureconomique_situation_institutionfinanciere_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='acteureconomique',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude GPS (ex: 6.9057 pour Kpalimé)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='acteureconomique',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude GPS (ex: 0.6287 pour Kpalimé)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='institutionfinanciere',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude GPS (ex: 6.9057 pour Kpalimé)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='institutionfinanciere',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude GPS (ex: 0.6287 pour Kpalimé)', max_digits=9, null=True),
        ),
    ]
