# Generated by Django 6.0.3 on 2026-03-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acteurs', '0009_agents_collecteurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetouristique',
            name='photo_2',
            field=models.FileField(blank=True, upload_to='sites/photos/'),
        ),
        migrations.AddField(
            model_name='sitetouristique',
            name='photo_3',
            field=models.FileField(blank=True, upload_to='sites/photos/'),
        ),
        migrations.AddField(
            model_name='sitetouristique',
            name='photo_4',
            field=models.FileField(blank=True, upload_to='sites/photos/'),
        ),
        migrations.AlterField(
            model_name='sitetouristique',
            name='categorie_site',
            field=models.CharField(choices=[('cascade', 'Cascade'), ('montagne', 'Montagne'), ('foret', 'Forêt'), ('plage', 'Plage'), ('parc', 'Parc'), ('monument', 'Monument'), ('musee', 'Musée'), ('site_culturel', 'Site culturel'), ('site_historique', 'Site historique'), ('site_religieux', 'Site religieux'), ('bibliotheque', 'Bibliothèque'), ('place_publique', 'Place publique'), ('autre', 'Autre')], max_length=60),
        ),
    ]
