# Generated by Django 6.0.2 on 2026-02-16 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationSocieteCivile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_osc', models.CharField(max_length=255, verbose_name="Nom de l'OSC")),
                ('sigle', models.CharField(blank=True, max_length=100, verbose_name='Sigle')),
                ('type_osc', models.CharField(max_length=255, verbose_name="Type d'OSC")),
                ('date_creation', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('domaines_intervention', models.TextField(blank=True, help_text="Liste des domaines d'intervention (un par ligne).", verbose_name="Domaines d'intervention")),
                ('membres_responsables', models.TextField(blank=True, help_text='Liste des membres et de leurs fonctions (un par ligne).', verbose_name='Membres / Responsables')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('est_valide_par_mairie', models.BooleanField(default=False, verbose_name='Validé par la mairie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations_societe_civile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé')),
            ],
            options={
                'verbose_name': 'Organisation de la Société Civile',
                'verbose_name_plural': 'Organisations de la Société Civile',
                'ordering': ['-date_enregistrement'],
            },
        ),
    ]
