# Generated by Django 6.0.2

import osc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationsocietecivile",
            name="papiers_justificatifs",
            field=models.FileField(
                blank=True,
                help_text="Document PDF optionnel (statuts, récépissé, etc.). Max 5 Mo.",
                null=True,
                upload_to="osc/papiers/",
                validators=[osc.models.validate_osc_file],
                verbose_name="Papiers justificatifs (PDF)",
            ),
        ),
    ]
