"""
Django settings for mairie_kloto_platform project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6o61dhf@=_%a3f2wnnowoko-qojozah)-!jdg%$28#-f*#a0g3'

# SECURITY WARNING: don't run with debug turned on in production!
# Détecter si on est sur PythonAnywhere
import os
ON_PYTHONANYWHERE = 'PYTHONANYWHERE_DOMAIN' in os.environ or 'pythonanywhere.com' in os.environ.get('HTTP_HOST', '')

DEBUG = not ON_PYTHONANYWHERE  # False sur PythonAnywhere, True en local

if ON_PYTHONANYWHERE:
    ALLOWED_HOSTS = ['mariekloto1tg.pythonanywhere.com', 'www.mariekloto1tg.pythonanywhere.com']
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'jazzmin',          # Thème moderne pour l'admin Django
    'admin_interface',  # Doit être avant django.contrib.admin
    'colorfield',       # Dépendance de admin_interface
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mairie_kloto_platform',  # Pour les commandes de gestion personnalisées
    'mairie',  # Informations de la mairie (mot du maire, collaborateurs, etc.)
    'acteurs',
    'emploi',
    'actualites',
    'comptes',  # Gestion de l'authentification
    'diaspora',  # Enregistrement et gestion de la diaspora
    'osc',  # Organisations de la Société Civile
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mairie_kloto_platform.middleware.TrackVisitorMiddleware',
]

ROOT_URLCONF = 'mairie_kloto_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mairie.context_processors.mairie_config',
                'mairie.context_processors.publicite_globale',
                'mairie.context_processors.partenaires_footer',
            ],
        },
    },
]

WSGI_APPLICATION = 'mairie_kloto_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Authentication backends
# Permet la connexion avec le nom d'utilisateur OU l'email
AUTHENTICATION_BACKENDS = [
    'mairie_kloto_platform.backends.EmailOrUsernameBackend',  # Backend personnalisé (email ou username)
    'django.contrib.auth.backends.ModelBackend',  # Backend par défaut Django
]

# URL de redirection après connexion
LOGIN_URL = '/comptes/connexion/'
LOGIN_REDIRECT_URL = '/enregistrement/'
LOGOUT_REDIRECT_URL = '/'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Africa/Lome'  # Fuseau horaire du Togo

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
if ON_PYTHONANYWHERE:
    STATIC_ROOT = '/home/mariekloto1tg/MairieKloto1/staticfiles'
else:
    STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
if ON_PYTHONANYWHERE:
    MEDIA_ROOT = '/home/mariekloto1tg/MairieKloto1/media'
else:
    MEDIA_ROOT = BASE_DIR / 'media'

# Email configuration (development)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@mairie-kloto.tg'
