# Generated by Django 6.0 on 2025-12-19 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=150)),
                ('fonction', models.CharField(choices=[('maire', 'Maire'), ('premier_adjoint', 'Premier Adjoint au Maire'), ('adjoint', 'Adjoint au Maire'), ('secretaire_general', 'Secrétaire Général'), ('directeur', 'Directeur'), ('chef_service', 'Chef de Service'), ('conseiller', 'Conseiller Municipal'), ('autre', 'Autre')], help_text='Fonction dans la mairie', max_length=50)),
                ('fonction_custom', models.CharField(blank=True, help_text="Fonction personnalisée (si 'Autre' est sélectionné)", max_length=255)),
                ('photo', models.ImageField(blank=True, help_text='Photo du collaborateur', null=True, upload_to='mairie/collaborateurs/')),
                ('telephone', models.CharField(blank=True, help_text='Numéro de téléphone', max_length=30)),
                ('email', models.EmailField(blank=True, help_text='Adresse email', max_length=254)),
                ('bureau', models.CharField(blank=True, help_text="Localisation du bureau (ex: 'Bureau 101, 1er étage')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description des responsabilités et compétences')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier, plus grand = plus bas)")),
                ('est_visible', models.BooleanField(default=True, help_text="Afficher ce collaborateur sur la page d'accueil")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collaborateur',
                'verbose_name_plural': 'Collaborateurs',
                'ordering': ['ordre_affichage', 'fonction', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='InformationMairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_info', models.CharField(choices=[('contact', 'Contact'), ('horaire', 'Horaires'), ('adresse', 'Adresse'), ('mission', 'Mission/Vision'), ('histoire', 'Histoire'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('icone', models.CharField(blank=True, help_text="Icône (ex: '📞', '🕒', '📍', etc.)", max_length=50)),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('est_visible', models.BooleanField(default=True, help_text="Afficher cette information sur la page d'accueil")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Information mairie',
                'verbose_name_plural': 'Informations mairie',
                'ordering': ['ordre_affichage', 'type_info', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='MotMaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Mot du Maire', help_text="Titre du message (ex: 'Mot du Maire', 'Bienvenue', etc.)", max_length=255)),
                ('contenu', models.TextField(help_text='Message de bienvenue du maire (minimum 50 caractères)', validators=[django.core.validators.MinLengthValidator(50)])),
                ('nom_maire', models.CharField(help_text='Nom complet du maire', max_length=255)),
                ('photo_maire', models.ImageField(blank=True, help_text='Photo du maire', null=True, upload_to='mairie/photos/')),
                ('signature', models.ImageField(blank=True, help_text='Signature du maire', null=True, upload_to='mairie/signatures/')),
                ('est_actif', models.BooleanField(default=True, help_text="Afficher ce message sur la page d'accueil")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mot du maire',
                'verbose_name_plural': 'Mots du maire',
                'ordering': ['-date_modification'],
            },
        ),
    ]
