# Generated by Django 6.0 on 2025-12-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, help_text="Référence interne de l'appel d'offres (ex: A0-2025-001).", max_length=100)),
                ('description', models.TextField(help_text="Description détaillée de l'appel d'offres, objet, objectifs, conditions.")),
                ('public_cible', models.CharField(choices=[('entreprises', 'Entreprises / Acteurs économiques'), ('institutions', 'Institutions financières'), ('jeunes', "Jeunes en quête d'emploi"), ('retraites', 'Retraités actifs'), ('tous', 'Tout le monde')], default='tous', help_text="Public principalement visé par cet appel d'offres.", max_length=20)),
                ('date_debut', models.DateTimeField(help_text="Date et heure d'ouverture de l'appel d'offres.")),
                ('date_fin', models.DateTimeField(help_text="Date et heure de clôture de l'appel d'offres.")),
                ('budget_estime', models.DecimalField(blank=True, decimal_places=2, help_text='Budget estimé ou montant indicatif (facultatif).', max_digits=15, null=True)),
                ('document_officiel', models.FileField(blank=True, help_text="Cahier des charges ou document officiel de l'appel d'offres (PDF, DOC, etc.).", null=True, upload_to='mairie/appels_offres/')),
                ('criteres_selection', models.TextField(blank=True, help_text='Résumé des critères de sélection (facultatif, pour affichage rapide).')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('cloture', 'Clôturé'), ('archive', 'Archivé')], default='brouillon', help_text="Statut de l'appel d'offres.", max_length=20)),
                ('est_publie_sur_site', models.BooleanField(default=False, help_text="Cocher pour afficher cet appel d'offres sur la plateforme publique.")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Appel d'offres",
                'verbose_name_plural': "Appels d'offres",
                'ordering': ['-date_debut', '-date_creation'],
            },
        ),
    ]
