# Generated by Django 6.0 on 2025-12-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0002_appeloffre'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='dossier_candidature',
            field=models.TextField(blank=True, help_text='Liste des pièces à fournir pour le dossier de candidature.'),
        ),
    ]
