# Generated by Django 6.0 on 2025-12-30 09:35

import django.db.models.deletion
import mairie.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0003_appeloffre_dossier_candidature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_dossier', models.FileField(help_text='Dossier complet (PDF uniquement, max 5 Mo).', upload_to='mairie/candidatures/', validators=[mairie.models.validate_file_size], verbose_name='Dossier de candidature (PDF)')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20, verbose_name='Statut de la candidature')),
                ('message_accompagnement', models.TextField(blank=True, verbose_name="Message d'accompagnement (facultatif)")),
                ('appel_offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='mairie.appeloffre', verbose_name="Appel d'offres concerné")),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL, verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-date_soumission'],
                'unique_together': {('appel_offre', 'candidat')},
            },
        ),
    ]
