# Generated by Django 6.0 on 2025-12-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0004_candidature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image pour le carousel (recommandé: 1920x800px ou ratio 16:9)', upload_to='mairie/carousel/')),
                ('titre', models.CharField(blank=True, help_text="Titre optionnel pour l'image", max_length=255)),
                ('description', models.TextField(blank=True, help_text="Description optionnelle pour l'image")),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier, plus grand = plus bas)")),
                ('est_actif', models.BooleanField(default=True, help_text='Afficher cette image dans le carousel')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image carousel',
                'verbose_name_plural': 'Images carousel',
                'ordering': ['ordre_affichage', '-date_creation'],
            },
        ),
    ]
