# Generated by Django 6.0 on 2026-01-06 08:11

import mairie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0007_restore_candidature_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationMairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commune', models.CharField(default='Mairie de Kloto 1', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='mairie/logo/', validators=[mairie.models.validate_file_size])),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration de la mairie',
                'verbose_name_plural': 'Configuration de la mairie',
                'ordering': ['-date_modification'],
            },
        ),
    ]
