# Generated by Django 6.0 on 2026-01-06 08:17

import mairie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0008_configurationmairie'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationmairie',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='mairie/favicon/', validators=[mairie.models.validate_file_size]),
        ),
    ]
