# Generated by Django 4.2.16 on 2026-01-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0010_configurationmairie_contact_reseaux'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiteSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('session_key', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'Visite du site',
                'verbose_name_plural': 'Visites du site',
                'ordering': ['-date'],
            },
        ),
    ]
