# Generated by Django 4.2.16 on 2026-01-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0011_visitesite'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatCivilPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex: Acte de naissance, Transcription, Acte de mariage…', max_length=255)),
                ('slug', models.SlugField(help_text='Identifiant technique (ex: acte-naissance). Utilisé pour l’ancrage sur la page publique.', max_length=255, unique=True)),
                ('resume', models.TextField(blank=True, help_text='Petit résumé qui apparaîtra sous le titre (facultatif).')),
                ('contenu', models.TextField(help_text='Description détaillée de la démarche : pièces à fournir, coût, délais, service compétent, etc.')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage sur la page (0 = en haut).")),
                ('est_visible', models.BooleanField(default=True, help_text='Cocher pour afficher cette rubrique dans l’onglet État civil.')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Page d'état civil",
                'verbose_name_plural': "Pages d'état civil",
                'ordering': ['ordre_affichage', 'titre'],
            },
        ),
    ]
