# Generated by Django 6.0.1 on 2026-01-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0012_etatcivilpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeloffre',
            name='public_cible',
            field=models.CharField(choices=[('entreprises', 'Entreprises / Acteurs économiques'), ('institutions', 'Institutions financières'), ('entreprises_institutions', 'Entreprises et Institutions financières'), ('jeunes', "Jeunes en quête d'emploi"), ('retraites', 'Retraités actifs'), ('tous', 'Tout le monde')], default='tous', help_text="Public principalement visé par cet appel d'offres.", max_length=30),
        ),
    ]
