# Generated by Django 6.0.1 on 2026-01-14 08:34

import django.db.models.deletion
import mairie.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0013_alter_appeloffre_public_cible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagnePublicitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Objectif de la campagne, produits ou services mis en avant…')),
                ('duree_jours', models.PositiveIntegerField(default=30, help_text='Durée standard de diffusion des publicités (en jours).')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, help_text='Montant payé pour cette campagne (rempli par la mairie).', max_digits=12, null=True)),
                ('statut', models.CharField(choices=[('demande', 'Demande en attente de validation'), ('acceptee', 'Acceptée par la mairie (en attente de paiement)'), ('payee', "Payée (en attente d'activation)"), ('active', 'Active'), ('terminee', 'Terminée')], default='demande', help_text='Statut de la campagne dans le circuit mairie / paiement.', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True, help_text='Date de création de la demande de campagne.')),
                ('date_debut', models.DateTimeField(blank=True, help_text='Date de début effective de diffusion (optionnelle, fixée par la mairie).', null=True)),
                ('date_fin', models.DateTimeField(blank=True, help_text='Date de fin effective de diffusion (optionnelle, fixée par la mairie).', null=True)),
                ('proprietaire', models.ForeignKey(help_text='Utilisateur propriétaire de la campagne (entreprise ou institution financière).', on_delete=django.db.models.deletion.CASCADE, related_name='campagnes_publicitaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campagne publicitaire',
                'verbose_name_plural': 'Campagnes publicitaires',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('texte', models.TextField(help_text='Texte du message publicitaire qui sera affiché dans la fenêtre modale.')),
                ('image', models.ImageField(blank=True, help_text='Visuel de la publicité (optionnel).', null=True, upload_to='mairie/publicites/', validators=[mairie.models.validate_file_size])),
                ('url_cible', models.URLField(blank=True, help_text="Lien vers le site ou la page de l'entreprise (optionnel).")),
                ('est_active', models.BooleanField(default=True, help_text='Seules les publicités actives peuvent être affichées sur le site.')),
                ('date_debut', models.DateTimeField(blank=True, help_text='Date de début de diffusion de cette publicité (facultatif).', null=True)),
                ('date_fin', models.DateTimeField(blank=True, help_text='Date de fin de diffusion de cette publicité (facultatif).', null=True)),
                ('ordre_priorite', models.PositiveIntegerField(default=0, help_text='Permet de donner la priorité à certaines pubs (0 = priorité normale).')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(help_text='Campagne à laquelle cette publicité est rattachée.', on_delete=django.db.models.deletion.CASCADE, related_name='publicites', to='mairie.campagnepublicitaire')),
            ],
            options={
                'verbose_name': 'Publicité',
                'verbose_name_plural': 'Publicités',
                'ordering': ['ordre_priorite', '-date_creation'],
            },
        ),
    ]
