# Generated by Django 6.0.1 on 2026-01-24 07:01

import django.db.models.deletion
import mairie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0015_projet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo descriptive du projet (max 5 Mo)', upload_to='mairie/projets/galerie/', validators=[mairie.models.validate_file_size])),
                ('legende', models.CharField(blank=True, help_text='Légende optionnelle pour décrire la photo', max_length=255)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = première, 1 = deuxième, etc.)")),
                ('projet', models.ForeignKey(help_text='Projet concerné', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='mairie.projet')),
            ],
            options={
                'verbose_name': 'Photo du projet',
                'verbose_name_plural': 'Photos du projet',
                'ordering': ['ordre', 'pk'],
            },
        ),
    ]
