# Generated by Django 6.0.1 on 2026-01-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0020_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonMairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_donateur', models.CharField(help_text='Nom complet du donateur', max_length=255)),
                ('email', models.EmailField(help_text='Adresse email du donateur', max_length=254)),
                ('telephone', models.CharField(blank=True, help_text='Numéro de téléphone (facultatif)', max_length=50)),
                ('type_don', models.CharField(choices=[('yas_money', 'Yas Money'), ('flooz_money', 'Flooz Money'), ('carte_bancaire', 'Carte Bancaire')], help_text='Moyen de paiement utilisé pour le don', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant du don en FCFA', max_digits=15)),
                ('message', models.TextField(blank=True, help_text='Message optionnel du donateur')),
                ('date_don', models.DateTimeField(auto_now_add=True, help_text='Date et heure du don')),
                ('est_confirme', models.BooleanField(default=False, help_text='Marquer comme confirmé après vérification du paiement')),
                ('date_confirmation', models.DateTimeField(blank=True, help_text='Date de confirmation du don', null=True)),
                ('notes_admin', models.TextField(blank=True, help_text="Notes internes de l'administration")),
            ],
            options={
                'verbose_name': 'Don à la Mairie',
                'verbose_name_plural': 'Dons à la Mairie',
                'ordering': ['-date_don'],
            },
        ),
        migrations.AddField(
            model_name='configurationmairie',
            name='numero_carte_bancaire',
            field=models.CharField(blank=True, help_text='Numéro de compte Carte Bancaire pour les dons', max_length=50),
        ),
        migrations.AddField(
            model_name='configurationmairie',
            name='numero_flooz_money',
            field=models.CharField(blank=True, help_text='Numéro de compte Flooz Money pour les dons (ex: +228 XX XX XX XX)', max_length=50),
        ),
        migrations.AddField(
            model_name='configurationmairie',
            name='numero_yas_money',
            field=models.CharField(blank=True, help_text='Numéro de compte Yas Money pour les dons (ex: +228 XX XX XX XX)', max_length=50),
        ),
    ]
