# Generated by Django 6.0.1 on 2026-01-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0021_donmairie_configurationmairie_numero_carte_bancaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecarousel',
            name='bouton1_texte',
            field=models.CharField(blank=True, help_text="Texte du premier bouton (ex: 'En savoir plus'). Laisser vide pour utiliser un texte par défaut.", max_length=100),
        ),
        migrations.AddField(
            model_name='imagecarousel',
            name='bouton1_url',
            field=models.URLField(blank=True, help_text="URL du premier bouton. Si vide, le bouton n'apparaîtra pas."),
        ),
        migrations.AddField(
            model_name='imagecarousel',
            name='bouton2_texte',
            field=models.CharField(blank=True, help_text='Texte du deuxième bouton (facultatif).', max_length=100),
        ),
        migrations.AddField(
            model_name='imagecarousel',
            name='bouton2_url',
            field=models.URLField(blank=True, help_text='URL du deuxième bouton (facultatif).'),
        ),
        migrations.AddField(
            model_name='imagecarousel',
            name='bouton3_texte',
            field=models.CharField(blank=True, help_text='Texte du troisième bouton (facultatif).', max_length=100),
        ),
        migrations.AddField(
            model_name='imagecarousel',
            name='bouton3_url',
            field=models.URLField(blank=True, help_text='URL du troisième bouton (facultatif).'),
        ),
        migrations.AlterField(
            model_name='configurationmairie',
            name='numero_carte_bancaire',
            field=models.CharField(blank=True, help_text='Numéro de compte bancaire pour les dons (affiché publiquement sur le site)', max_length=50),
        ),
        migrations.AlterField(
            model_name='configurationmairie',
            name='numero_flooz_money',
            field=models.CharField(blank=True, help_text='Syntaxe ou code de transfert Flooz Money (ex: *155*1*...#). Ce code ne sera pas affiché, uniquement utilisé pour le lien.', max_length=50),
        ),
        migrations.AlterField(
            model_name='configurationmairie',
            name='numero_yas_money',
            field=models.CharField(blank=True, help_text='Syntaxe ou code de transfert Mixx by Yas (ex: *145*1*...#). Ce code ne sera pas affiché, uniquement utilisé pour le lien.', max_length=50),
        ),
    ]
