# Generated by Django 6.0.2 on 2026-02-18 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0022_imagecarousel_bouton1_texte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartographieCommune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie_km2', models.PositiveIntegerField(help_text='Superficie totale de la commune en km² (ex: 146).')),
                ('population_totale', models.PositiveIntegerField(help_text='Population totale estimée de la commune.')),
                ('densite_hab_km2', models.PositiveIntegerField(help_text='Densité moyenne (habitants par km²).')),
                ('taux_natalite_pour_mille', models.DecimalField(decimal_places=2, help_text='Taux de natalité pour 1000 habitants (ex: 32.50).', max_digits=5)),
                ('taux_mortalite_pour_mille', models.DecimalField(decimal_places=2, help_text='Taux de mortalité pour 1000 habitants (ex: 7.80).', max_digits=5)),
                ('taux_croissance_pourcent', models.DecimalField(decimal_places=2, help_text='Taux annuel moyen de croissance de la population en % (ex: 2.30).', max_digits=5)),
                ('principales_activites', models.TextField(help_text='Principales activités économiques (une activité par ligne).')),
                ('infrastructures_sante', models.TextField(help_text='Liste des infrastructures de santé (une par ligne).')),
                ('infrastructures_education', models.TextField(help_text='Liste des infrastructures éducatives (une par ligne).')),
                ('infrastructures_routes', models.TextField(help_text='Axes routiers, voiries, pistes (une par ligne).')),
                ('infrastructures_administration', models.TextField(help_text='Principales infrastructures administratives et de services publics (une par ligne).')),
                ('centre_latitude', models.DecimalField(decimal_places=6, help_text='Latitude du centre de la commune pour la carte (ex: 6.900000).', max_digits=9)),
                ('centre_longitude', models.DecimalField(decimal_places=6, help_text='Longitude du centre de la commune pour la carte (ex: 0.630000).', max_digits=9)),
                ('zoom_carte', models.PositiveIntegerField(default=13, help_text='Niveau de zoom par défaut de la carte (ex: 13).')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('configuration', models.OneToOneField(help_text='Configuration associée à cette commune.', on_delete=django.db.models.deletion.CASCADE, related_name='cartographie', to='mairie.configurationmairie')),
            ],
            options={
                'verbose_name': 'Cartographie de la commune',
                'verbose_name_plural': 'Cartographie de la commune',
                'ordering': ['-date_modification'],
            },
        ),
    ]
