# Generated by Django 6.0.2 on 2026-02-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0023_cartographiecommune'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Adresse email de l'abonné à la newsletter.", max_length=254, unique=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True, help_text="Date et heure d'inscription.")),
                ('est_actif', models.BooleanField(default=True, help_text='Permet de désactiver un contact sans le supprimer.')),
                ('source', models.CharField(blank=True, help_text="Source d'inscription (ex: popup, formulaire footer...).", max_length=50)),
            ],
            options={
                'verbose_name': 'Inscription à la newsletter',
                'verbose_name_plural': 'Inscriptions à la newsletter',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
