# Generated by Django 6.0.2 on 2026-02-18 14:56

import mairie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0024_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du partenaire', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Logo du partenaire (optionnel)', null=True, upload_to='mairie/partenaires/', validators=[mairie.models.validate_file_size])),
                ('url_site', models.URLField(blank=True, help_text='Lien vers le site du partenaire (optionnel)', max_length=500)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (plus petit = plus haut)")),
                ('est_actif', models.BooleanField(default=True, help_text='Afficher ce partenaire dans le footer')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
