# Generated by Django 6.0.2 on 2026-02-24 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0030_cotisations_acteurs_institutions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionMairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom complet de la direction (ex: Direction des affaires administratives, ressources humaines et état civil).', max_length=255)),
                ('sigle', models.CharField(blank=True, help_text='Sigle de la direction (ex: DAARHEC).', max_length=50)),
                ('chef_direction', models.CharField(help_text='Nom du Chef de direction.', max_length=255)),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans l'organigramme (de gauche à droite).")),
                ('est_active', models.BooleanField(default=True, help_text="Afficher cette direction dans l'organigramme public.")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Direction de la mairie',
                'verbose_name_plural': 'Directions de la mairie',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenoms', models.CharField(help_text='Nom et prénoms du membre du personnel.', max_length=255)),
                ('adresse', models.CharField(blank=True, help_text='Adresse (facultatif).', max_length=255)),
                ('contact', models.CharField(blank=True, help_text='Contact téléphonique ou email.', max_length=100)),
                ('fonction', models.CharField(help_text='Fonction occupée dans la section.', max_length=255)),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans la section.")),
                ('est_actif', models.BooleanField(default=True, help_text="Afficher ce membre du personnel dans l'organigramme public.")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personnel de section',
                'verbose_name_plural': 'Personnel des sections',
                'ordering': ['section', 'ordre_affichage', 'nom_prenoms'],
            },
        ),
        migrations.CreateModel(
            name='SectionDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom complet de la section.', max_length=255)),
                ('sigle', models.CharField(blank=True, help_text='Sigle de la section (facultatif).', max_length=50)),
                ('chef_section', models.CharField(blank=True, help_text='Nom du Chef de section.', max_length=255)),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage de la section à l'intérieur de la direction.")),
                ('est_active', models.BooleanField(default=True, help_text="Afficher cette section dans l'organigramme public.")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('direction', models.ForeignKey(help_text='Direction à laquelle cette section est rattachée.', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='mairie.directionmairie')),
            ],
            options={
                'verbose_name': 'Section de direction',
                'verbose_name_plural': 'Sections de direction',
                'ordering': ['direction', 'ordre_affichage', 'nom'],
            },
        ),
        migrations.DeleteModel(
            name='EtatCivilPage',
        ),
        migrations.AlterField(
            model_name='paiementcotisation',
            name='encaisse_par',
            field=models.ForeignKey(blank=True, help_text='[Déprécié] Utiliser encaisse_par_agent. Conservé pour compatibilité.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_cotisations_encaisses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketmarche',
            name='encaisse_par',
            field=models.ForeignKey(blank=True, help_text='[Déprécié] Utiliser encaisse_par_agent. Conservé pour compatibilité.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_marche_encaisses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personnelsection',
            name='section',
            field=models.ForeignKey(help_text='Section à laquelle ce membre du personnel est rattaché.', on_delete=django.db.models.deletion.CASCADE, related_name='personnels', to='mairie.sectiondirection'),
        ),
    ]
