# Generated by Django 6.0.2 on 2026-02-24 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0031_directionmairie_personnelsection_sectiondirection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre du service.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description des missions et activités du service (facultatif).')),
                ('responsable', models.CharField(blank=True, help_text='Nom du responsable du service (facultatif).', max_length=255)),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage du service dans la section.")),
                ('est_actif', models.BooleanField(default=True, help_text="Afficher ce service dans l'organigramme public.")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(help_text='Section à laquelle ce service est rattaché.', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='mairie.sectiondirection')),
            ],
            options={
                'verbose_name': 'Service de section',
                'verbose_name_plural': 'Services de section',
                'ordering': ['section', 'ordre_affichage', 'titre'],
            },
        ),
    ]
