# Generated by Django 6.0.2 on 2026-02-24 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0032_servicesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureCommune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_infrastructure', models.CharField(choices=[('sante', 'Infrastructure de santé'), ('education', 'Infrastructure éducative'), ('voirie', 'Réseau viaire et voirie'), ('administration', 'Administration / service public')], help_text="Catégorie d'infrastructure (santé, éducation, voirie, administration).", max_length=20)),
                ('nom', models.CharField(help_text="Nom de l'infrastructure (ex: Centre de santé de Kpodzi).", max_length=255)),
                ('description', models.TextField(blank=True, help_text="Description synthétique de l'infrastructure et de ses services (facultatif).")),
                ('adresse', models.CharField(blank=True, help_text='Adresse ou quartier (facultatif).', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude du point (ex: 6.903421).', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude du point (ex: 0.627845).', max_digits=9)),
                ('est_active', models.BooleanField(default=True, help_text='Afficher cette infrastructure sur la carte publique.')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cartographie', models.ForeignKey(help_text='Fiche de cartographie à laquelle cette infrastructure est rattachée.', on_delete=django.db.models.deletion.CASCADE, related_name='infrastructures', to='mairie.cartographiecommune')),
            ],
            options={
                'verbose_name': 'Infrastructure de la commune',
                'verbose_name_plural': 'Infrastructures de la commune',
                'ordering': ['cartographie', 'type_infrastructure', 'nom'],
            },
        ),
    ]
