# Generated by Django 6.0.2 on 2026-02-25 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0033_infrastructurecommune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiondirection',
            name='direction',
            field=models.ForeignKey(help_text='Direction à laquelle cette section est rattachée (pour compatibilité).', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='mairie.directionmairie'),
        ),
        migrations.CreateModel(
            name='DivisionDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom complet de la division.', max_length=255)),
                ('sigle', models.CharField(blank=True, help_text='Sigle de la division (facultatif).', max_length=50)),
                ('chef_division', models.CharField(blank=True, help_text='Nom du Chef de division (facultatif).', max_length=255)),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage de la division à l'intérieur de la direction.")),
                ('est_active', models.BooleanField(default=True, help_text="Afficher cette division dans l'organigramme public.")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('direction', models.ForeignKey(help_text='Direction à laquelle cette division est rattachée.', on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='mairie.directionmairie')),
            ],
            options={
                'verbose_name': 'Division de direction',
                'verbose_name_plural': 'Divisions de direction',
                'ordering': ['direction', 'ordre_affichage', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='sectiondirection',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Division à laquelle cette section est rattachée (niveau intermédiaire).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='mairie.divisiondirection'),
        ),
    ]
