# Generated by Django 6.0.2 on 2026-02-28 16:29

import django.db.models.deletion
import mairie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0035_videospot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videospot',
            name='fichier_video',
            field=models.FileField(blank=True, help_text='Fichier vidéo court (ex: spot de 5 minutes, max 25 Mo).', null=True, upload_to='mairie/videos_spots/', validators=[mairie.models.validate_video_size]),
        ),
        migrations.CreateModel(
            name='InformationMairieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Image illustrative pour ce bloc d'information.", upload_to='mairie/informations/', validators=[mairie.models.validate_file_size])),
                ('legende', models.CharField(blank=True, help_text="Légende facultative affichée sous l'image.", max_length=255)),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage des images pour cette information.")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('information', models.ForeignKey(help_text='Information à laquelle cette image est rattachée.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mairie.informationmairie')),
            ],
            options={
                'verbose_name': 'Image pour information mairie',
                'verbose_name_plural': 'Images pour informations mairie',
                'ordering': ['information', 'ordre_affichage', 'pk'],
            },
        ),
    ]
