# Generated by Django 6.0.3 on 2026-03-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0036_alter_videospot_fichier_video_informationmairieimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code technique du type de local (ex: boutique, magasin).', max_length=50, unique=True)),
                ('nom', models.CharField(help_text='Libellé affiché pour le type de local.', max_length=100)),
                ('est_actif', models.BooleanField(default=True, help_text='Permet de masquer ce type sans le supprimer.')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de local (marché)',
                'verbose_name_plural': 'Types de locaux (marché)',
                'ordering': ['nom'],
            },
        ),
    ]
