from django.core.management.base import BaseCommand
from datetime import date, datetime
from decimal import Decimal

from acteurs.models import ActeurEconomique, InstitutionFinanciere
from emploi.models import ProfilEmploi


class Command(BaseCommand):
    help = "Ajoute des données de test dans la base de données"

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS("Début de l'ajout des données de test..."))

        # 1. Ajouter 5 Acteurs économiques
        self.stdout.write("\n1. Ajout de 5 Acteurs économiques...")
        acteurs_data = [
            {
                "raison_sociale": "Entreprise de Commerce Général Kpalimé",
                "type_acteur": "commerce",
                "secteur_activite": "commerce",
                "statut_juridique": "ei",
                "description": "Commerce général de produits alimentaires et de première nécessité dans le centre-ville de Kpalimé.",
                "rccm": "TG-KPA-2024-001",
                "ifu": "1234567890123",
                "date_creation": date(2020, 1, 15),
                "capital_social": Decimal("5000000.00"),
                "nom_responsable": "Koffi Mensah",
                "fonction_responsable": "Gérant",
                "telephone1": "+22890123456",
                "telephone2": "+22890123457",
                "email": "commerce.kpalime@example.com",
                "site_web": "https://commerce-kpalime.example.com",
                "quartier": "Centre-ville",
                "canton": "Kpalimé",
                "adresse_complete": "Avenue principale, face à la mairie",
                "nombre_employes": "1-5",
                "chiffre_affaires": "5M-20M",
                "certifie_information": True,
                "accepte_conditions": True,
                "accepte_public": True,
            },
            {
                "raison_sociale": "Artisanat et Services Kloto",
                "type_acteur": "artisan",
                "secteur_activite": "artisanat",
                "statut_juridique": "ei",
                "description": "Atelier d'artisanat spécialisé dans la fabrication de meubles en bois et objets décoratifs.",
                "rccm": "TG-KPA-2023-045",
                "ifu": "2345678901234",
                "date_creation": date(2019, 6, 10),
                "capital_social": Decimal("2000000.00"),
                "nom_responsable": "Ama Adjovi",
                "fonction_responsable": "Artisan principal",
                "telephone1": "+22890234567",
                "email": "artisanat.kloto@example.com",
                "quartier": "Quartier Artisanal",
                "canton": "Kpalimé",
                "adresse_complete": "Zone artisanale, route de Badou",
                "nombre_employes": "1-5",
                "chiffre_affaires": "0-5M",
                "certifie_information": True,
                "accepte_conditions": True,
                "accepte_public": True,
            },
            {
                "raison_sociale": "PME Transport et Logistique",
                "type_acteur": "pme",
                "secteur_activite": "transport",
                "statut_juridique": "sarl",
                "description": "Entreprise de transport de marchandises et de personnes dans la région des Plateaux.",
                "rccm": "TG-KPA-2022-078",
                "ifu": "3456789012345",
                "date_creation": date(2018, 3, 20),
                "capital_social": Decimal("10000000.00"),
                "nom_responsable": "Komlan Agbessi",
                "fonction_responsable": "Directeur Général",
                "telephone1": "+22890345678",
                "telephone2": "+22890345679",
                "email": "transport.kloto@example.com",
                "quartier": "Gare routière",
                "canton": "Kpalimé",
                "adresse_complete": "Gare routière principale, parking des bus",
                "nombre_employes": "11-50",
                "chiffre_affaires": "20M-50M",
                "certifie_information": True,
                "accepte_conditions": True,
                "accepte_public": True,
            },
            {
                "raison_sociale": "ONG Développement Rural Kloto",
                "type_acteur": "ong",
                "secteur_activite": "agriculture",
                "statut_juridique": "ong",
                "description": "Organisation non gouvernementale œuvrant pour le développement agricole et rural dans la commune de Kloto 1.",
                "rccm": "TG-KPA-2021-112",
                "date_creation": date(2017, 9, 5),
                "nom_responsable": "Yawa Togbé",
                "fonction_responsable": "Coordinatrice",
                "telephone1": "+22890456789",
                "email": "ong.kloto@example.com",
                "site_web": "https://ong-kloto.example.com",
                "quartier": "Quartier Administratif",
                "canton": "Kpalimé",
                "adresse_complete": "Bureau administratif, près de la préfecture",
                "nombre_employes": "6-10",
                "chiffre_affaires": "0-5M",
                "certifie_information": True,
                "accepte_conditions": True,
                "accepte_public": True,
            },
            {
                "raison_sociale": "Restaurant et Hôtellerie Les Plateaux",
                "type_acteur": "entreprise",
                "secteur_activite": "hotellerie",
                "statut_juridique": "sarl",
                "description": "Restaurant et hôtel de charme offrant des services d'hébergement et de restauration aux visiteurs de Kpalimé.",
                "rccm": "TG-KPA-2024-156",
                "ifu": "4567890123456",
                "date_creation": date(2021, 11, 12),
                "capital_social": Decimal("25000000.00"),
                "nom_responsable": "Kossi Amégan",
                "fonction_responsable": "Directeur",
                "telephone1": "+22890567890",
                "telephone2": "+22890567891",
                "email": "hotel.plateaux@example.com",
                "site_web": "https://hotel-plateaux.example.com",
                "quartier": "Zone touristique",
                "canton": "Kpalimé",
                "adresse_complete": "Route de la cascade, zone touristique",
                "nombre_employes": "11-50",
                "chiffre_affaires": "50M-100M",
                "certifie_information": True,
                "accepte_conditions": True,
                "accepte_public": True,
            },
        ]

        for i, data in enumerate(acteurs_data, 1):
            acteur, created = ActeurEconomique.objects.get_or_create(
                raison_sociale=data["raison_sociale"],
                defaults=data
            )
            if created:
                self.stdout.write(
                    self.style.SUCCESS(f"  ✓ Acteur économique {i} créé : {acteur.raison_sociale}")
                )
            else:
                self.stdout.write(
                    self.style.WARNING(f"  - Acteur économique {i} existe déjà : {acteur.raison_sociale}")
                )

        # 2. Ajouter 5 Institutions financières
        self.stdout.write("\n2. Ajout de 5 Institutions financières...")
        institutions_data = [
            {
                "type_institution": "banque",
                "nom_institution": "Banque Commerciale de Kloto",
                "sigle": "BCK",
                "annee_creation": 2015,
                "numero_agrement": "BCEAO-TOGO-2015-001",
                "ifu": "9876543210987",
                "description_services": "Services bancaires complets : comptes courants, épargne, crédits aux entreprises et particuliers, transferts d'argent.",
                "services": "comptes,epargne,credits,transfert,mobile",
                "taux_credit": "12%",
                "taux_epargne": "5%",
                "nom_responsable": "Dr. Yao Koffi",
                "fonction_responsable": "Directeur Régional",
                "telephone1": "+22890678901",
                "telephone2": "+22890678902",
                "whatsapp": "+22890678901",
                "email": "contact@bck-togo.com",
                "site_web": "https://bck-togo.com",
                "facebook": "https://facebook.com/bck-togo",
                "quartier": "Centre-ville",
                "canton": "Kpalimé",
                "adresse_complete": "Avenue principale, immeuble BCK",
                "nombre_agences": 2,
                "horaires": "Lundi-Vendredi: 8h-17h, Samedi: 8h-13h",
                "certifie_info": True,
                "accepte_public": True,
                "accepte_contact": True,
                "engagement": True,
            },
            {
                "type_institution": "microfinance",
                "nom_institution": "Institution de Microfinance Solidarité",
                "sigle": "IMS",
                "annee_creation": 2010,
                "numero_agrement": "MINFI-TOGO-2010-045",
                "ifu": "8765432109876",
                "description_services": "Micro-crédits pour les PME, épargne, crédits agricoles et accompagnement des entrepreneurs.",
                "services": "microCredits,epargne,agricole,conseil",
                "taux_credit": "18%",
                "taux_epargne": "6%",
                "nom_responsable": "Mme. Adjoa Kossi",
                "fonction_responsable": "Directrice",
                "telephone1": "+22890789012",
                "whatsapp": "+22890789012",
                "email": "contact@ims-togo.com",
                "quartier": "Marché central",
                "canton": "Kpalimé",
                "adresse_complete": "Près du marché central, bâtiment IMS",
                "nombre_agences": 1,
                "horaires": "Lundi-Samedi: 8h-16h",
                "certifie_info": True,
                "accepte_public": True,
                "accepte_contact": True,
                "engagement": True,
            },
            {
                "type_institution": "cooperative",
                "nom_institution": "Coopérative d'Épargne et de Crédit de Kloto",
                "sigle": "CECK",
                "annee_creation": 2012,
                "numero_agrement": "MINFI-TOGO-2012-089",
                "description_services": "Coopérative offrant des services d'épargne, de crédit et d'assurance mutuelle aux membres de la commune.",
                "services": "epargne,credits,assurance",
                "taux_credit": "15%",
                "taux_epargne": "5.5%",
                "nom_responsable": "Kouassi Amégan",
                "fonction_responsable": "Président",
                "telephone1": "+22890890123",
                "email": "contact@ceck-togo.com",
                "quartier": "Quartier résidentiel",
                "canton": "Kpalimé",
                "adresse_complete": "Siège social, quartier résidentiel",
                "nombre_agences": 1,
                "horaires": "Lundi-Vendredi: 9h-15h",
                "certifie_info": True,
                "accepte_public": True,
                "accepte_contact": True,
                "engagement": True,
            },
            {
                "type_institution": "assurance",
                "nom_institution": "Compagnie d'Assurance Kloto",
                "sigle": "CAK",
                "annee_creation": 2018,
                "numero_agrement": "MINFI-TOGO-2018-234",
                "ifu": "7654321098765",
                "description_services": "Assurance vie, assurance santé, assurance automobile et assurance habitation pour les particuliers et entreprises.",
                "services": "assurance,conseil",
                "nom_responsable": "M. Yao Mensah",
                "fonction_responsable": "Directeur Commercial",
                "telephone1": "+22890901234",
                "telephone2": "+22890901235",
                "email": "contact@cak-togo.com",
                "site_web": "https://cak-togo.com",
                "quartier": "Zone commerciale",
                "canton": "Kpalimé",
                "adresse_complete": "Zone commerciale, immeuble CAK",
                "nombre_agences": 1,
                "horaires": "Lundi-Vendredi: 8h-17h",
                "certifie_info": True,
                "accepte_public": True,
                "accepte_contact": True,
                "engagement": True,
            },
            {
                "type_institution": "ong",
                "nom_institution": "ONG Financement Développement",
                "sigle": "OFD",
                "annee_creation": 2008,
                "numero_agrement": "MINFI-TOGO-2008-012",
                "description_services": "Financement de projets de développement, micro-crédits pour les femmes entrepreneures, accompagnement des jeunes entrepreneurs.",
                "services": "microCredits,pme,conseil,investissement",
                "nom_responsable": "Mme. Yawa Adjovi",
                "fonction_responsable": "Coordinatrice",
                "telephone1": "+22890012345",
                "whatsapp": "+22890012345",
                "email": "contact@ofd-togo.com",
                "facebook": "https://facebook.com/ofd-togo",
                "quartier": "Quartier Administratif",
                "canton": "Kpalimé",
                "adresse_complete": "Bureau administratif, zone ONG",
                "nombre_agences": 1,
                "horaires": "Lundi-Vendredi: 8h-16h",
                "certifie_info": True,
                "accepte_public": True,
                "accepte_contact": True,
                "engagement": True,
            },
        ]

        for i, data in enumerate(institutions_data, 1):
            institution, created = InstitutionFinanciere.objects.get_or_create(
                nom_institution=data["nom_institution"],
                defaults=data
            )
            if created:
                self.stdout.write(
                    self.style.SUCCESS(f"  ✓ Institution financière {i} créée : {institution.nom_institution}")
                )
            else:
                self.stdout.write(
                    self.style.WARNING(f"  - Institution financière {i} existe déjà : {institution.nom_institution}")
                )

        # 3. Ajouter 5 Jeunes demandeurs d'emploi
        self.stdout.write("\n3. Ajout de 5 Jeunes demandeurs d'emploi...")
        jeunes_data = [
            {
                "type_profil": "jeune",
                "nom": "Koffi",
                "prenoms": "Komlan",
                "sexe": "masculin",
                "date_naissance": date(1998, 5, 15),
                "nationalite": "Togolaise",
                "telephone1": "+22891111111",
                "telephone2": "+22891111112",
                "email": "komlan.koffi@example.com",
                "quartier": "Centre-ville",
                "canton": "Kpalimé",
                "adresse_complete": "Rue principale, maison n°45",
                "est_resident_kloto": True,
                "niveau_etude": "licence",
                "diplome_principal": "Licence en Gestion",
                "situation_actuelle": "sans_emploi",
                "domaine_competence": "Comptabilité, gestion administrative, secrétariat",
                "experiences": "Stage de 3 mois dans une entreprise de commerce",
                "disponibilite": "immediate",
                "type_contrat_souhaite": "cdi",
                "salaire_souhaite": "150000 FCFA",
                "accepte_rgpd": True,
                "accepte_contact": True,
            },
            {
                "type_profil": "jeune",
                "nom": "Adjovi",
                "prenoms": "Ama",
                "sexe": "feminin",
                "date_naissance": date(2000, 8, 22),
                "nationalite": "Togolaise",
                "telephone1": "+22892222222",
                "email": "ama.adjovi@example.com",
                "quartier": "Quartier Artisanal",
                "canton": "Kpalimé",
                "adresse_complete": "Zone artisanale, parcelle 12",
                "est_resident_kloto": True,
                "niveau_etude": "bts",
                "diplome_principal": "BTS en Informatique",
                "situation_actuelle": "etudiant",
                "domaine_competence": "Développement web, maintenance informatique, réseaux",
                "experiences": "Projets personnels de développement web",
                "disponibilite": "1_mois",
                "type_contrat_souhaite": "cdd",
                "salaire_souhaite": "120000 FCFA",
                "accepte_rgpd": True,
                "accepte_contact": True,
            },
            {
                "type_profil": "jeune",
                "nom": "Mensah",
                "prenoms": "Kossi",
                "sexe": "masculin",
                "date_naissance": date(1997, 3, 10),
                "nationalite": "Togolaise",
                "telephone1": "+22893333333",
                "email": "kossi.mensah@example.com",
                "quartier": "Zone touristique",
                "canton": "Kpalimé",
                "adresse_complete": "Route de la cascade, maison n°8",
                "est_resident_kloto": True,
                "niveau_etude": "bac",
                "diplome_principal": "BAC série D",
                "situation_actuelle": "sans_emploi",
                "domaine_competence": "Tourisme, accueil, guide touristique, hôtellerie",
                "experiences": "Stage dans un hôtel pendant les vacances",
                "disponibilite": "immediate",
                "type_contrat_souhaite": "cdd",
                "salaire_souhaite": "100000 FCFA",
                "accepte_rgpd": True,
                "accepte_contact": True,
            },
            {
                "type_profil": "jeune",
                "nom": "Togbé",
                "prenoms": "Yawa",
                "sexe": "feminin",
                "date_naissance": date(1999, 11, 5),
                "nationalite": "Togolaise",
                "telephone1": "+22894444444",
                "email": "yawa.togbe@example.com",
                "quartier": "Marché central",
                "canton": "Kpalimé",
                "adresse_complete": "Près du marché, rue commerçante",
                "est_resident_kloto": True,
                "niveau_etude": "master",
                "diplome_principal": "Master en Commerce International",
                "situation_actuelle": "en_emploi",
                "employeur_actuel": "Entreprise de commerce",
                "domaine_competence": "Commerce international, marketing, vente, négociation",
                "experiences": "2 ans d'expérience en vente et marketing",
                "disponibilite": "3_mois",
                "type_contrat_souhaite": "cdi",
                "salaire_souhaite": "200000 FCFA",
                "accepte_rgpd": True,
                "accepte_contact": True,
            },
            {
                "type_profil": "jeune",
                "nom": "Amégan",
                "prenoms": "Kouassi",
                "sexe": "masculin",
                "date_naissance": date(1996, 7, 18),
                "nationalite": "Togolaise",
                "telephone1": "+22895555555",
                "email": "kouassi.amegan@example.com",
                "quartier": "Quartier résidentiel",
                "canton": "Kpalimé",
                "adresse_complete": "Quartier résidentiel, avenue des fleurs",
                "est_resident_kloto": True,
                "niveau_etude": "licence",
                "diplome_principal": "Licence en Agriculture",
                "situation_actuelle": "sans_emploi",
                "domaine_competence": "Agriculture, élevage, techniques agricoles modernes",
                "experiences": "Stage dans une ferme agricole, projets personnels de maraîchage",
                "disponibilite": "immediate",
                "type_contrat_souhaite": "cdd",
                "salaire_souhaite": "130000 FCFA",
                "accepte_rgpd": True,
                "accepte_contact": True,
            },
        ]

        for i, data in enumerate(jeunes_data, 1):
            jeune, created = ProfilEmploi.objects.get_or_create(
                email=data["email"],
                defaults=data
            )
            if created:
                self.stdout.write(
                    self.style.SUCCESS(f"  ✓ Jeune demandeur d'emploi {i} créé : {jeune.nom} {jeune.prenoms}")
                )
            else:
                self.stdout.write(
                    self.style.WARNING(f"  - Jeune demandeur d'emploi {i} existe déjà : {jeune.nom} {jeune.prenoms}")
                )

        # 4. Ajouter 5 Retraités actifs
        self.stdout.write("\n4. Ajout de 5 Retraités actifs...")
        retraites_data = [
            {
                "type_profil": "retraite",
                "nom": "Koffi",
                "prenoms": "Yao",
                "sexe": "masculin",
                "date_naissance": date(1955, 4, 20),
                "nationalite": "Togolaise",
                "telephone1": "+22896666666",
                "email": "yao.koffi@example.com",
                "quartier": "Centre-ville",
                "canton": "Kpalimé",
                "adresse_complete": "Avenue principale, résidence Koffi",
                "est_resident_kloto": True,
                "niveau_etude": "master",
                "diplome_principal": "Master en Administration",
                "situation_actuelle": "retraite",
                "employeur_actuel": "Ancien fonctionnaire",
                "caisse_retraite": "CNSS",
                "domaine_competence": "Administration publique, gestion, comptabilité",
                "experiences": "35 ans d'expérience dans l'administration publique, directeur de service",
                "dernier_poste": "Directeur de Service Administratif",
                "annees_experience": 35,
                "disponibilite": "immediate",
                "type_contrat_souhaite": "mission",
                "salaire_souhaite": "300000 FCFA",
                "accepte_rgpd": True,
                "accepte_contact": True,
            },
            {
                "type_profil": "retraite",
                "nom": "Adjovi",
                "prenoms": "Adjoa",
                "sexe": "feminin",
                "date_naissance": date(1958, 9, 12),
                "nationalite": "Togolaise",
                "telephone1": "+22897777777",
                "email": "adjoa.adjovi@example.com",
                "quartier": "Quartier Administratif",
                "canton": "Kpalimé",
                "adresse_complete": "Zone administrative, villa Adjovi",
                "est_resident_kloto": True,
                "niveau_etude": "licence",
                "diplome_principal": "Licence en Éducation",
                "situation_actuelle": "retraite",
                "caisse_retraite": "CNSS",
                "domaine_competence": "Enseignement, formation, pédagogie",
                "experiences": "30 ans d'expérience dans l'enseignement primaire et secondaire",
                "dernier_poste": "Directrice d'École Primaire",
                "annees_experience": 30,
                "disponibilite": "immediate",
                "type_contrat_souhaite": "mission",
                "salaire_souhaite": "250000 FCFA",
                "accepte_rgpd": True,
                "accepte_contact": True,
            },
            {
                "type_profil": "retraite",
                "nom": "Mensah",
                "prenoms": "Komlan",
                "sexe": "masculin",
                "date_naissance": date(1953, 2, 28),
                "nationalite": "Togolaise",
                "telephone1": "+22898888888",
                "email": "komlan.mensah@example.com",
                "quartier": "Zone commerciale",
                "canton": "Kpalimé",
                "adresse_complete": "Zone commerciale, résidence Mensah",
                "est_resident_kloto": True,
                "niveau_etude": "bts",
                "diplome_principal": "BTS en Bâtiment",
                "situation_actuelle": "retraite",
                "caisse_retraite": "CNSS",
                "domaine_competence": "Bâtiment, construction, travaux publics, maçonnerie",
                "experiences": "40 ans d'expérience dans le bâtiment et les travaux publics",
                "dernier_poste": "Chef de Chantier",
                "annees_experience": 40,
                "disponibilite": "immediate",
                "type_contrat_souhaite": "mission",
                "salaire_souhaite": "280000 FCFA",
                "accepte_rgpd": True,
                "accepte_contact": True,
            },
            {
                "type_profil": "retraite",
                "nom": "Togbé",
                "prenoms": "Yawa",
                "sexe": "feminin",
                "date_naissance": date(1956, 6, 15),
                "nationalite": "Togolaise",
                "telephone1": "+22899999999",
                "email": "yawa.togbe@example.com",
                "quartier": "Quartier résidentiel",
                "canton": "Kpalimé",
                "adresse_complete": "Quartier résidentiel, maison Togbé",
                "est_resident_kloto": True,
                "niveau_etude": "licence",
                "diplome_principal": "Licence en Santé",
                "situation_actuelle": "retraite",
                "caisse_retraite": "CNSS",
                "domaine_competence": "Santé, soins infirmiers, santé communautaire",
                "experiences": "32 ans d'expérience comme infirmière dans les centres de santé",
                "dernier_poste": "Infirmière Principale",
                "annees_experience": 32,
                "disponibilite": "immediate",
                "type_contrat_souhaite": "mission",
                "salaire_souhaite": "270000 FCFA",
                "accepte_rgpd": True,
                "accepte_contact": True,
            },
            {
                "type_profil": "retraite",
                "nom": "Amégan",
                "prenoms": "Kossi",
                "sexe": "masculin",
                "date_naissance": date(1954, 12, 8),
                "nationalite": "Togolaise",
                "telephone1": "+22890000000",
                "email": "kossi.amegan@example.com",
                "quartier": "Zone touristique",
                "canton": "Kpalimé",
                "adresse_complete": "Route de la cascade, résidence Amégan",
                "est_resident_kloto": True,
                "niveau_etude": "bac",
                "diplome_principal": "BAC série G",
                "situation_actuelle": "retraite",
                "caisse_retraite": "CNSS",
                "domaine_competence": "Agriculture, agronomie, développement rural",
                "experiences": "38 ans d'expérience dans l'agriculture et le développement rural",
                "dernier_poste": "Technicien Agricole Principal",
                "annees_experience": 38,
                "disponibilite": "immediate",
                "type_contrat_souhaite": "mission",
                "salaire_souhaite": "260000 FCFA",
                "accepte_rgpd": True,
                "accepte_contact": True,
            },
        ]

        for i, data in enumerate(retraites_data, 1):
            retraite, created = ProfilEmploi.objects.get_or_create(
                email=data["email"],
                defaults=data
            )
            if created:
                self.stdout.write(
                    self.style.SUCCESS(f"  ✓ Retraité actif {i} créé : {retraite.nom} {retraite.prenoms}")
                )
            else:
                self.stdout.write(
                    self.style.WARNING(f"  - Retraité actif {i} existe déjà : {retraite.nom} {retraite.prenoms}")
                )

        self.stdout.write(self.style.SUCCESS("\n✓ Ajout des données de test terminé avec succès !"))

