# Generated by Django 6.0 on 2025-12-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('resume', models.TextField(blank=True, help_text="Court résumé qui apparaît sur la page d'accueil.")),
                ('contenu', models.TextField(help_text="Contenu détaillé de l'actualité.")),
                ('photo1', models.FileField(blank=True, help_text='Première photo', null=True, upload_to='actualites/photos/')),
                ('photo2', models.FileField(blank=True, help_text='Deuxième photo', null=True, upload_to='actualites/photos/')),
                ('photo3', models.FileField(blank=True, help_text='Troisième photo', null=True, upload_to='actualites/photos/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('est_publie', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication'],
            },
        ),
    ]
